### PR TITLE
Vector Store, Storing and Loading Indices.

### PR DESCRIPTION
**Pull request by greeshmavamsi**
created functions to :
- Create Vector Store (FAISS)
- Store indices in the vector store
- Load indices from vector store

### CODE REVIEW

**Comment by harshit82** [comment]
@greeshmavamsi can you create a function to combine all these functions in the embedder as a single point of calling

**Comment by greeshmavamsi** [comment]
@harshit82 function 'invoke_embedder' added for orchestrating all other functions

**Comment by harshit82** [comment]
Unnecessary parameter 'index path' in function 'invoke embedder'

**Comment by greeshmavamsi** [comment]
> Unnecessary parameter 'index path' in function 'invoke embedder'

done.

**Review by harshit82 — COMMENTED** [review]
LGTM

**Review by harshit82 — APPROVED** [review]

**Pull request merged**
